version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://db:3306/rotacore
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - db
    networks:
      - rotacore-net

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: rotacore
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306" # Expose on 3307 to avoid conflict with local MySQL
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rotacore-net

networks:
  rotacore-net:
    driver: bridge

volumes:
  db_data:
